### ISSUE TITLE
Tasks inside blocks/rescue/always are not added to the generated documentation

### ISSUE THREAD

**Issue by ksatchit** [starboarder2001/ansible-docgen#32]
Hi @starboarder2001 , @nickpack 

Found ansible-docgen to be a great tool to document my roles and playbooks. Thanks for building it !

I see that tasks inside ansible block are not added to the documentation. Provided below is a sample playbook and corresponding documentation : 

Playbook
-----------
```
# Author: ksatchit
# Description: ansible-docgen issues with block


- hosts: localhost

  tasks:

    - name: First task in the playbook
      shell: echo "PRINT TASK1"

    - block:
        - name: Second task in the playbook, first in the do block
          shell: echo "PRINT TASK2"

      rescue:
        - name: Third task in playbook, first in the rescue block
          shell: echo "PRINT TASK3"

      always:
        - name: Fourth task in playbook, first in the always block
          shell: echo "PRINT TASK4"
```
README.md
--------------
```
## Playbook: [sampletest.yml](sampletest.yml)
> **Author:** ksatchit

> **Description:** ansible-docgen issues with block

> **Task:** First task in the playbook
```
